apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: dns-status-internal
  namespace: kuberhealthy
spec:
  runInterval: 1m
  timeout: 2m
  podSpec:
    serviceAccountName: dns-internal-check
    containers:
      - env:
          - name: HOSTNAME
            # value: "hostnames-headless.default"
            # value: "hostnames.default"
            value: "idontexist"
          - name: NAMESPACE
            value: "kube-system"
          - name: DNS_NODE_SELECTOR
            value: k8s-app=kube-dns
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        # image: kuberhealthy/dns-resolution-check:v1.4.3
        image: omegavveapon/kuberhealthy-internal-dns-check:working-check
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
