apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: dns-internal-check
  namespace: kuberhealthy
spec:
  runInterval: 2m
  timeout: 3m
  podSpec:
    serviceAccountName: dns-internal-check
    containers:
      - env:
          - name: ANNOTATION
            value: "please-check-me"
          - name: DNS_NAMESPACE
            value: "kube-system"
          - name: DNS_NODE_SELECTOR
            value: "k8s-app=kube-dns"
          - name: MAX_SERVICES
            value: "1"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: omegavveapon/kuberhealthy-internal-dns-check:working-check
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
